FROM alpine/git
WORKDIR /sergeyKargopolov
RUN git clone https://github.com/7289983355/orderService.git



FROM maven:3.5-jdk-8-alpine
WORKDIR /sergeyKargopolov
COPY --from=0 /sergeyKargopolov/orderService/  /sergeyKargopolov
RUN mvn install 

FROM openjdk:8-jre-alpine
WORKDIR /sergeyKargopolov
COPY --from=1 /orderService/target/orderService-0.0.1-SNAPSHOT.jar (4)
CMD ["java -jar orderService-0.0.1-SNAPSHOT.jar"] (5)




